name: Build and test container app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install application dependencies
      - name: Install dependencies
        working-directory: ./app
        run: npm install

      # Test the apps     
      - name: test
        working-directory: ./app
        run: npm run test
          
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./app
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_HUB_USER_NAME }}/review-service:${{ github.sha }}
        file: ./app/Dockerfile
        

